services:
  api:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-8003}:8000"
    depends_on: []
    env_file:
      - .env
    networks:
      - default
      - postgres-net
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT:-3003}:80"
    depends_on:
      - api
    networks:
      - default
    restart: always

networks:
  default:
  postgres-net:
    external: true
