"""add_sender_subject_filter_to_cleanup_jobs

Revision ID: 57b510cb1e17
Revises: 943a8d1ac672
Create Date: 2026-03-15 17:29:56.034231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b510cb1e17'
down_revision = '943a8d1ac672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleanup_jobs', sa.Column('sender_filter', sa.String(length=255), nullable=True))
    op.add_column('cleanup_jobs', sa.Column('subject_filter', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cleanup_jobs', 'subject_filter')
    op.drop_column('cleanup_jobs', 'sender_filter')
    # ### end Alembic commands ###
