"""add_google_auth_broken_to_users

Revision ID: 5daf64374ea5
Revises: 57b510cb1e17
Create Date: 2026-03-23 14:59:42.382716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5daf64374ea5'
down_revision = '57b510cb1e17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_auth_broken', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_auth_broken')
    # ### end Alembic commands ###
