"""add_stop_on_match_to_rules

Revision ID: 9a7f5c2d1b4e
Revises: c3f1e4d8b7a2
Create Date: 2026-04-21 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a7f5c2d1b4e"
down_revision = "c3f1e4d8b7a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules",
        sa.Column("stop_on_match", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("rules", "stop_on_match", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules", "stop_on_match")
    # ### end Alembic commands ###
