"""add_match_from_exclude_to_rules

Revision ID: c3f1e4d8b7a2
Revises: 5daf64374ea5
Create Date: 2026-04-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3f1e4d8b7a2"
down_revision = "5daf64374ea5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rules", sa.Column("match_from_exclude", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules", "match_from_exclude")
    # ### end Alembic commands ###
