"""initial_schema

Revision ID: f84b4fec0a8b
Revises: 
Create Date: 2026-03-13 08:12:08.854430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84b4fec0a8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_provider', sa.String(length=64), nullable=True),
    sa.Column('ai_api_key', sa.Text(), nullable=True),
    sa.Column('last_history_id', sa.String(length=255), nullable=True),
    sa.Column('polling_enabled', sa.Boolean(), nullable=False),
    sa.Column('polling_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cleanup_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label_filter', sa.String(length=255), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('processed_messages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gmail_label_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label_type', sa.String(length=32), nullable=False),
    sa.Column('color_bg', sa.String(length=32), nullable=True),
    sa.Column('color_text', sa.String(length=32), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_label_id')
    )
    op.create_table('system_label_retention',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('match_from', sa.String(length=255), nullable=True),
    sa.Column('match_to', sa.String(length=255), nullable=True),
    sa.Column('match_subject', sa.String(length=255), nullable=True),
    sa.Column('match_has_words', sa.Text(), nullable=True),
    sa.Column('match_doesnt_have', sa.Text(), nullable=True),
    sa.Column('match_label_id', sa.Integer(), nullable=True),
    sa.Column('action_label_id', sa.Integer(), nullable=True),
    sa.Column('action_archive', sa.Boolean(), nullable=False),
    sa.Column('action_delete', sa.Boolean(), nullable=False),
    sa.Column('action_mark_read', sa.Boolean(), nullable=False),
    sa.Column('action_delete_after_days', sa.Integer(), nullable=True),
    sa.Column('scope_promotions', sa.Boolean(), nullable=False),
    sa.Column('scope_social', sa.Boolean(), nullable=False),
    sa.Column('scope_updates', sa.Boolean(), nullable=False),
    sa.Column('scope_forums', sa.Boolean(), nullable=False),
    sa.Column('use_ai', sa.Boolean(), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['match_label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    op.drop_table('system_label_retention')
    op.drop_table('labels')
    op.drop_table('cleanup_jobs')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
